import type { LeaveRecord } from "./types";

/**
 * Temporary/mock data for the Manage Leave List feature.
 *
 * This is intentionally varied (multiple employees, categories, payment
 * types, leave durations, date ranges, and reason lengths) so pagination,
 * search, column filters, date filters, and sorting can all be exercised.
 *
 * Replace this module with a real API call later — see the `loadLeaveRecords`
 * helper in `LeaveTable.tsx` for where that swap happens.
 */
export const leaveRecords: LeaveRecord[] = [
  {
    id: "LV-1001",
    employeeName: "Sakshi Deshmukh",
    leaveCategory: "General Leave",
    type: "Paid",
    dateFrom: "2026-05-02",
    dateTo: "2026-05-03",
    leaveType: "Full Day",
    reason: "I will be travelling to visit family for a wedding.",
  },
  {
    id: "LV-1002",
    employeeName: "Rohan Patil",
    leaveCategory: "Sick Leave",
    type: "Paid",
    dateFrom: "2026-05-05",
    dateTo: "2026-05-05",
    leaveType: "Full Day",
    reason: "Fever and doctor-advised rest.",
  },
  {
    id: "LV-1003",
    employeeName: "Ananya Kulkarni",
    leaveCategory: "Casual Leave",
    type: "Unpaid",
    dateFrom: "2026-05-06",
    dateTo: "2026-05-06",
    leaveType: "Half Day",
    reason: "Personal appointment in the morning.",
  },
  {
    id: "LV-1004",
    employeeName: "Vikram Singh",
    leaveCategory: "General Leave",
    type: "Paid",
    dateFrom: "2026-05-08",
    dateTo: "2026-05-12",
    leaveType: "Full Day",
    reason: "Travelling out of town for a family function, returning the following Monday.",
  },
  {
    id: "LV-1005",
    employeeName: "Priya Nair",
    leaveCategory: "Maternity Leave",
    type: "Paid",
    dateFrom: "2026-05-10",
    dateTo: "2026-08-10",
    leaveType: "Full Day",
    reason: "Approved maternity leave as per policy.",
  },
  {
    id: "LV-1006",
    employeeName: "Aditya Joshi",
    leaveCategory: "Casual Leave",
    type: "Unpaid",
    dateFrom: "2026-05-11",
    dateTo: "2026-05-11",
    leaveType: "Short Leave",
    reason: "Stepping out for two hours to collect documents.",
  },
  {
    id: "LV-1007",
    employeeName: "Neha Choudhary",
    leaveCategory: "Sick Leave",
    type: "Paid",
    dateFrom: "2026-05-13",
    dateTo: "2026-05-14",
    leaveType: "Full Day",
    reason: "Recovering from a minor surgery, doctor recommended two days of rest.",
  },
  {
    id: "LV-1008",
    employeeName: "Karan Mehta",
    leaveCategory: "General Leave",
    type: "Paid",
    dateFrom: "2026-05-15",
    dateTo: "2026-05-15",
    leaveType: "Half Day",
    reason: "Attending a sibling's graduation ceremony.",
  },
  {
    id: "LV-1009",
    employeeName: "Ishita Rao",
    leaveCategory: "Casual Leave",
    type: "Paid",
    dateFrom: "2026-05-16",
    dateTo: "2026-05-16",
    leaveType: "Full Day",
    reason: "I will be travelling for a friend's engagement.",
  },
  {
    id: "LV-1010",
    employeeName: "Siddharth Kapoor",
    leaveCategory: "General Leave",
    type: "Unpaid",
    dateFrom: "2026-05-18",
    dateTo: "2026-05-20",
    leaveType: "Full Day",
    reason: "Unplanned home repair work needs to be supervised on-site.",
  },
  {
    id: "LV-1011",
    employeeName: "Meera Iyer",
    leaveCategory: "Sick Leave",
    type: "Paid",
    dateFrom: "2026-05-19",
    dateTo: "2026-05-19",
    leaveType: "Short Leave",
    reason: "Dental appointment in the afternoon.",
  },
  {
    id: "LV-1012",
    employeeName: "Arjun Reddy",
    leaveCategory: "Casual Leave",
    type: "Paid",
    dateFrom: "2026-05-21",
    dateTo: "2026-05-21",
    leaveType: "Full Day",
    reason: "Local errands that could not be scheduled on a weekend.",
  },
  {
    id: "LV-1013",
    employeeName: "Sneha Pillai",
    leaveCategory: "General Leave",
    type: "Paid",
    dateFrom: "2026-05-22",
    dateTo: "2026-05-24",
    leaveType: "Full Day",
    reason: "Travelling with family for a short vacation before the monsoon.",
  },
  {
    id: "LV-1014",
    employeeName: "Devansh Gupta",
    leaveCategory: "Sick Leave",
    type: "Unpaid",
    dateFrom: "2026-05-25",
    dateTo: "2026-05-26",
    leaveType: "Full Day",
    reason: "Ongoing viral infection, extending rest by doctor's advice.",
  },
  {
    id: "LV-1015",
    employeeName: "Kavya Menon",
    leaveCategory: "General Leave",
    type: "Paid",
    dateFrom: "2026-06-01",
    dateTo: "2026-06-01",
    leaveType: "Half Day",
    reason: "Parent-teacher meeting at child's school.",
  },
  {
    id: "LV-1016",
    employeeName: "Rahul Verma",
    leaveCategory: "Casual Leave",
    type: "Paid",
    dateFrom: "2026-06-02",
    dateTo: "2026-06-03",
    leaveType: "Full Day",
    reason: "Attending a cousin's wedding in another city.",
  },
  {
    id: "LV-1017",
    employeeName: "Tanvi Shah",
    leaveCategory: "General Leave",
    type: "Unpaid",
    dateFrom: "2026-06-04",
    dateTo: "2026-06-04",
    leaveType: "Short Leave",
    reason: "Bank work that can only be done during working hours.",
  },
  {
    id: "LV-1018",
    employeeName: "Yash Trivedi",
    leaveCategory: "Sick Leave",
    type: "Paid",
    dateFrom: "2026-06-05",
    dateTo: "2026-06-05",
    leaveType: "Full Day",
    reason: "Migraine, unable to work at the screen for extended periods.",
  },
  {
    id: "LV-1019",
    employeeName: "Pooja Bhatt",
    leaveCategory: "Casual Leave",
    type: "Paid",
    dateFrom: "2026-06-08",
    dateTo: "2026-06-08",
    leaveType: "Full Day",
    reason: "Travelling home for a religious festival with family.",
  },
  {
    id: "LV-1020",
    employeeName: "Nikhil Anand",
    leaveCategory: "General Leave",
    type: "Paid",
    dateFrom: "2026-06-10",
    dateTo: "2026-06-12",
    leaveType: "Full Day",
    reason: "Pre-planned trip booked before the current sprint started, approved by manager in advance.",
  },
  {
    id: "LV-1021",
    employeeName: "Divya Krishnan",
    leaveCategory: "Sick Leave",
    type: "Unpaid",
    dateFrom: "2026-06-11",
    dateTo: "2026-06-11",
    leaveType: "Half Day",
    reason: "Follow-up lab test in the morning.",
  },
  {
    id: "LV-1022",
    employeeName: "Manish Chawla",
    leaveCategory: "Casual Leave",
    type: "Paid",
    dateFrom: "2026-06-15",
    dateTo: "2026-06-15",
    leaveType: "Full Day",
    reason: "Helping a family member move to a new apartment.",
  },
  {
    id: "LV-1023",
    employeeName: "Radhika Suri",
    leaveCategory: "General Leave",
    type: "Paid",
    dateFrom: "2026-06-18",
    dateTo: "2026-06-19",
    leaveType: "Full Day",
    reason: "Travelling for an off-site team offsite that overlaps with a personal commitment.",
  },
  {
    id: "LV-1024",
    employeeName: "Farhan Sheikh",
    leaveCategory: "Casual Leave",
    type: "Unpaid",
    dateFrom: "2026-06-20",
    dateTo: "2026-06-20",
    leaveType: "Short Leave",
    reason: "Vehicle service appointment that only had a weekday slot available.",
  },
];